-- ============================================================
-- ANANTHAMPALLI VILLAGE VINAYAKA CHAVITHI 2026 (AVVC 2026)
-- SUPABASE ONE-CLICK DATABASE SCHEMA & SEED SCRIPT
-- ============================================================

-- 1. Create Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Admins Table
CREATE TABLE IF NOT EXISTS public.admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT DEFAULT 'ADMIN',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Donations Table
CREATE TABLE IF NOT EXISTS public.donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_number TEXT UNIQUE NOT NULL,
    donor_name TEXT NOT NULL,
    mobile TEXT,
    amount NUMERIC NOT NULL DEFAULT 0,
    payment_method TEXT DEFAULT 'CASH',
    sponsorship_title TEXT,
    date DATE DEFAULT CURRENT_DATE,
    collected_by TEXT,
    is_public INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Events Table
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    event_name TEXT,
    event_date DATE,
    date DATE,
    start_time TEXT,
    end_time TEXT,
    event_time TEXT,
    location TEXT,
    description TEXT,
    status TEXT DEFAULT 'UPCOMING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Food Prasadam Table
CREATE TABLE IF NOT EXISTS public.food (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    meal_type TEXT,
    date DATE,
    start_time TEXT,
    end_time TEXT,
    location TEXT,
    description TEXT,
    menu TEXT,
    items TEXT,
    servings TEXT,
    sponsor TEXT,
    status TEXT DEFAULT 'SCHEDULED',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create Expenses Table
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    description TEXT,
    date DATE DEFAULT CURRENT_DATE,
    recorded_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Create Competitions & Sports Winners Table
CREATE TABLE IF NOT EXISTS public.competitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_name TEXT NOT NULL,
    category TEXT DEFAULT 'Sports',
    captain_name TEXT,
    team_members TEXT,
    winner_name TEXT,
    runner_name TEXT,
    sponsor TEXT,
    event_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'COMPLETED',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Create Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'GENERAL',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) and allow public reading/writing for API
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.food ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Safely Drop existing policies if re-running script
DROP POLICY IF EXISTS "Allow public read/write access settings" ON public.settings;
DROP POLICY IF EXISTS "Allow public read/write access admins" ON public.admins;
DROP POLICY IF EXISTS "Allow public read/write access donations" ON public.donations;
DROP POLICY IF EXISTS "Allow public read/write access events" ON public.events;
DROP POLICY IF EXISTS "Allow public read/write access food" ON public.food;
DROP POLICY IF EXISTS "Allow public read/write access expenses" ON public.expenses;
DROP POLICY IF EXISTS "Allow public read/write access competitions" ON public.competitions;
DROP POLICY IF EXISTS "Allow public read/write access notifications" ON public.notifications;

-- Create Policies
CREATE POLICY "Allow public read/write access settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access admins" ON public.admins FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access donations" ON public.donations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access events" ON public.events FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access food" ON public.food FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access expenses" ON public.expenses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access competitions" ON public.competitions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access notifications" ON public.notifications FOR ALL USING (true) WITH CHECK (true);

-- Initial Seed Data for Settings
INSERT INTO public.settings (key, value) VALUES
('festival_name', 'ANANTHAMPALLI VILLAGE VINAYAKA CHAVITHI 2026'),
('festival_year', '2026'),
('village_name', 'Ananthampalli Village'),
('main_location', 'Ananthampalli Main Temple Street Mandap'),
('contact_person', 'Teja Narapareddy'),
('contact_number', '+91 76709 87767'),
('developer_contact', '7330863893'),
('developer_whatsapp', '7330863893'),
('developer_credit', 'KLIVOO NEXT GEN CRMS (A TENSPICK INITIATIVE)'),
('public_financial_summary', 'ON'),
('public_expenses_detail', 'ON'),
('donator_privacy_default', 'PUBLIC'),
('whatsapp_country_code', '91'),
('currency_symbol', '₹'),
('receipt_prefix', 'AVVC-2026-'),
('festival_start_date', '2026-09-14'),
('receipt_footer_text', 'DESIGNED AND DEVELOPED PROUDLY IN ANANTHAMPALLI BY KLIVOO NEXT GEN CRMS (A TENSPICK INITIATIVE) • Contact Developer: 7330863893 — WhatsApp Only')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Initial Seed Data for Admins
INSERT INTO public.admins (username, full_name, role) VALUES
('tejanarapareddy2@gmail.com', 'Teja Narapareddy', 'SUPER_ADMIN')
ON CONFLICT (username) DO NOTHING;

-- Initial Seed Data for Sample Donations
INSERT INTO public.donations (receipt_number, donor_name, mobile, amount, payment_method, sponsorship_title, date, collected_by, is_public) VALUES
('AVVC-2026-0001', 'Yaddala Ranjith Goud (Sunny)', '7670987767', 5000, 'UPI', 'Grand Mandap Decoration Sponsor', '2026-09-01', 'Teja Narapareddy', 1),
('AVVC-2026-0002', 'Surya Mohan Reddy', '7330863893', 10000, 'CASH', 'Maha Annadanam Sponsor', '2026-09-02', 'Teja Narapareddy', 1)
ON CONFLICT (receipt_number) DO NOTHING;

-- Sample Competitions Data
INSERT INTO public.competitions (game_name, category, captain_name, team_members, winner_name, runner_name, sponsor, event_date, status) VALUES
('Village Cricket Premier League', 'Sports', 'Rama Krishnam Raju', 'Raju (C), Sunny, Teja, Suresh, Mahesh, Shiva, Anil', 'Ananthampalli Super Kings (Captain: Rama Krishnam Raju)', 'Mandap Warriors (Captain: Sunny Goud)', 'Rama Krishnam Raju & Family', '2026-09-14', 'COMPLETED'),
('Traditional Kolatam & Rangoli Contest', 'Cultural', 'Saraswathi Devi', 'Saraswathi, Lakshmi, Radha, Priya', 'Gauri Youth Group', 'Village Women League', 'Village Committee', '2026-09-15', 'COMPLETED');

-- Sample Initial Notifications
INSERT INTO public.notifications (title, message, type) VALUES
('🏆 Sports Winner Announced', 'Ananthampalli Super Kings won 1st Place in Village Cricket Tournament (Captain: Rama Krishnam Raju)', 'COMPETITION'),
('🍲 Annadanam Schedule', 'Maha Annadanam on 2026-09-14 at Main Mandap Hall sponsored by Rama Krishnam Raju', 'FOOD');
